sonar.projectKey=flaskblog-pentest
sonar.projectName=FlaskBlog Security Analysis
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.python.version=3.12

sonar.exclusions=**/venv/**,**/__pycache__/**,**/migrations/**,**/static/**,**/tests/**

sonar.host.url=https://sonarqube.csse.canterbury.ac.nz

sonar.login=TOKEN_HERE
